# -*- coding: utf-8 -*-
"""Sedona's US History Unit 2 — Revolution and Independence (1754–1783).

Source: `8US2.1-2.3TESTTOPICS.odt` in her US History folder (2026-09-28) — the
teacher's own list of what the Unit 2 test covers, in three sections. It is a
TOPIC LIST, not notes: it names what is tested and says nothing about it. Her
class slides and textbook pages for Unit 2 are not in Drive, so the substance
here is standard US history, and every card and question is flagged
`from:'added'` — marking it `source` would put the school's name on facts its
own material never stated (the v197 rule). The objectives are `source`,
because the list really does say what is on the test.

Three parts, one per section of the list, shelving as `Unit 2` beside Unit 1.
All three are `prep:true` — a study unit built for a named test IS test prep
(v139, v194). Her class tests are multiple choice, primary sources,
fill-in-the-blank and short answer (syllabus), so the cards are built to be
SAID before flipping, and short primary-source passages appear where a real
one is short enough to quote exactly.

Two things on the list get deliberate airtime:
  • "Treaty of Paris" is under BOTH 2.1 and 2.3. They are two different
    treaties, 1763 and 1783, ending two different wars. Mixing them up is the
    likeliest wrong answer on the test.
  • The list spells her "Phyllis Wheatley". She signed herself PHILLIS — named
    for the Phillis, the ship that carried her from Africa. The card teaches
    the real spelling and says why.
"""
import unit_common as U

APP, CLS = 'ad-astra', 'history'
SRC = "History 8, Unit 2 test-topics list (teacher's, Drive)"
A = 'added'

def part(n, title, cards, qs, summary, why, objs, note, nxt, section):
    C, Q = [], []
    for c in cards: U.card(C, *c[:3], frm=A)
    for x in qs:
        passage = x[8] if len(x) > 8 else None
        kind = x[9] if len(x) > 9 else 'mc'
        U.q(Q, *x[:8], frm=A, kind=kind)
        if passage: Q[-1]['passage'] = passage
    U.build(APP, C, Q, 'unit-hist-u2p%d' % n, 'Unit 2 · %d %s' % (n, title), CLS,
            summary, why, objs, note, nxt, 'content/history-u2-p%d.json' % n,
            'US History Unit 2 test topics, section %s' % section, SRC,
            offset_hours=4, prep_=True, libv_=1)

DECL = ('We hold these truths to be self-evident, that all men are created equal, '
        'that they are endowed by their Creator with certain unalienable Rights, '
        'that among these are Life, Liberty and the pursuit of Happiness.')
PAINE2 = 'There is something very absurd, in supposing a continent to be perpetually governed by an island.'

# ══ Part 1 · The French and Indian War (topics 2.1) ══════════════════════════
part(1, 'The French and Indian War', [
 ('The French and Indian War (1754–1763)',
  '**A war between Britain and France for control of North America, fought in the colonies.**\n'
  '• The name comes from who the British colonists fought: the French and their Native allies.\n'
  '• It was part of a larger world war that Europe calls the Seven Years\' War.',
  'Named for the enemy, not for who fought on your side.'),
 ('Cause: the Ohio River Valley',
  '**Britain and France both claimed the land around the Ohio River.**\n'
  '• French forts and fur-trading posts stood in the way of colonists moving west.\n'
  '• Whoever held the valley controlled the trade and the route inland.',
  'Two empires, one river valley.'),
 ('Cause: land and the fur trade',
  '**The war was over who would profit from the land west of the colonies.**\n'
  '• France wanted furs and trade with Native nations.\n'
  '• British colonists wanted farmland to settle.',
  'France wanted trade; the colonists wanted farms.'),
 ('George Washington in 1754',
  '**A young Virginia militia officer whose clash with the French helped start the war.**\n'
  '• He built Fort Necessity and was forced to surrender it in 1754.\n'
  '• The experience made him one of the few colonists with real military command.',
  'His first fight was a loss — and it started a war.'),
 ('Native Americans in the war',
  '**Most Native nations sided with the French, who traded rather than settled.**\n'
  '• The Iroquois Confederacy leaned toward the British.\n'
  '• Native nations fought to protect their own lands, not for either empire.',
  'Traders were safer neighbours than settlers.'),
 ('The Treaty of Paris of 1763',
  '**The treaty that ENDED the French and Indian War, with Britain the winner.**\n'
  '• France gave up Canada and its land east of the Mississippi River to Britain.\n'
  '• France nearly vanished from the North American map.',
  '1763 — the FIRST Treaty of Paris. There is another one in 1783.'),
 ('Effect: a huge war debt',
  '**Britain won, but the war left it deeply in debt.**\n'
  '• Parliament decided the colonies should help pay for their own defence.\n'
  '• That decision leads straight to the new taxes of the 1760s.',
  'Winning cost money — and the bill went to the colonies.'),
 ('Effect: the end of being left alone',
  '**After the war Britain began enforcing its rules on the colonies much more strictly.**\n'
  '• Before 1763 it had mostly let the colonies run themselves.\n'
  '• Tighter control is what the colonists started to push back against.',
  'The war changed how Britain treated the colonies.'),
 ("Pontiac's Rebellion (1763)",
  '**An uprising by Native nations, led by the Ottawa leader Pontiac, against British forts in the west.**\n'
  '• With France gone, Native nations lost the ally that had balanced British settlers.\n'
  '• The fighting convinced Britain to try to separate settlers from Native lands.',
  'It is the reason for the Proclamation.'),
 ('The Proclamation of 1763',
  '**A British order banning colonists from settling west of the Appalachian Mountains.**\n'
  '• Its aim was to prevent more war with Native nations.\n'
  '• Colonists who had fought for that land were furious, and many ignored it.',
  'A line on the map along the mountains: no settling past here.'),
 ('Why colonists hated the Proclamation',
  '**They felt they had won the western land in the war and were now banned from it.**\n'
  '• Land speculators, including Washington, had money riding on the west.\n'
  '• It was the first sign that Britain would decide things over their heads.',
  'Fought for it, then told to stay out.'),
], [
 (1, 'What were Britain and France mainly competing for in the French and Indian War?',
  ['Control of land and trade in the Ohio River Valley',
   'Control of the sugar islands in the Caribbean Sea',
   'The right to tax the thirteen colonies directly',
   'Control of the Atlantic fishing grounds off Maine'], 0,
  'Think about where the fighting started.',
  ['Both empires claimed the land around the Ohio River.',
   'France wanted the fur trade there; British colonists wanted farmland.',
   'That rivalry is the cause of the war.'],
  '**Control of land and trade in the Ohio River Valley.** Whoever held the valley controlled the fur trade and the route west.',
  'Taxing the colonies comes AFTER the war, as one of its effects.'),
 (1, 'Why is it called the French and Indian War?',
  ['British colonists fought against the French and their Native allies',
   'The French and the Native nations fought against each other in it',
   'It was fought only in French Canada and on Native lands in the far west',
   'The French and Native nations signed the treaty that started it'], 0,
  'The name says who the colonists were fighting.',
  ['The war is named from the British colonists\' point of view.',
   'Their enemies were the French and the Native nations allied with France.',
   'So it is called the French and Indian War.'],
  '**The colonists fought the French and their Native allies.** The name names the enemy.',
  'Europe calls the wider conflict the Seven Years\' War.'),
 (1, 'What role did George Washington play at the start of the French and Indian War?',
  ['As a young Virginia officer, he clashed with the French and surrendered Fort Necessity',
   'As a British general, he captured Quebec and won the war for Britain',
   'As a delegate, he signed the Treaty of Paris that ended the war',
   'As a governor, he wrote the Proclamation of 1763 for Parliament'], 0,
  'He was young, and it did not go well for him.',
  ['In 1754 Washington led Virginia militia into the Ohio Valley.',
   'After a clash with the French he built Fort Necessity.',
   'He was forced to surrender it — and the fighting grew into a war.'],
  '**He clashed with the French and surrendered Fort Necessity.** His early defeat helped start the war.',
  'The same man will command the Continental Army twenty years later.'),
 (2, 'Why did most Native nations side with the French rather than the British?',
  ['The French mostly traded with them, while British colonists wanted their land',
   'The French promised to give every Native nation its own colony',
   'The British had already signed treaties giving the land to France',
   'The French army was larger than the British army in North America'], 0,
  'What did each side want from the land?',
  ['French settlers were few and came mainly to trade furs.',
   'British colonists came in large numbers and wanted farms.',
   'Farms meant taking Native land, so the French were the lesser threat.'],
  '**The French traded; the British settled.** Traders needed Native partners, settlers needed Native land.',
  'The Iroquois Confederacy was the main exception and leaned British.'),
 (1, 'What did the Treaty of Paris of 1763 do?',
  ['Ended the French and Indian War and gave Britain France\'s land east of the Mississippi',
   'Ended the American Revolution and recognised the United States as independent',
   'Started the French and Indian War by splitting the Ohio Valley in two',
   'Banned colonists from settling west of the Appalachian Mountains'], 0,
  'Which war was over in 1763?',
  ['1763 is the end of the French and Indian War.', 'Britain won.',
   'France gave up Canada and its lands east of the Mississippi to Britain.'],
  '**It ended the French and Indian War, with Britain taking France\'s eastern lands.**',
  'The 1783 Treaty of Paris ends a DIFFERENT war — the Revolution. Same name, twenty years apart.'),
 (2, 'Which was an effect of the French and Indian War on Britain?',
  ['A huge war debt that Britain wanted the colonies to help pay',
   'A new alliance between Britain and France against Spain',
   'The loss of all its colonies along the Atlantic coast',
   'A decision to let the colonies govern themselves completely'], 0,
  'Wars are expensive. Who paid?',
  ['Britain won the war but spent enormous sums on it.',
   'Parliament decided the colonists should share the cost.',
   'That led to new taxes on the colonies.'],
  '**A huge war debt.** Paying it off is why Britain began taxing the colonies.',
  'This effect is the bridge from topic 2.1 to topic 2.2.'),
 (2, 'What was the main purpose of the Proclamation of 1763?',
  ['To prevent more war with Native nations by keeping settlers east of the Appalachians',
   'To raise money for Britain by taxing every printed paper in the colonies',
   'To give the Ohio River Valley back to France as part of the peace',
   'To reward colonial soldiers with free farmland west of the mountains'], 0,
  "What had just happened in the west in 1763?",
  ["Pontiac's Rebellion showed Native nations would fight for their lands.",
   'Britain did not want to pay for another war.',
   'So it banned settlement west of the Appalachian Mountains.'],
  '**To prevent more war with Native nations.** The line along the Appalachians kept settlers and Native lands apart.',
  'Rewarding soldiers with western land is exactly what colonists EXPECTED — and did not get.'),
 (2, 'Why were many colonists angry about the Proclamation of 1763?',
  ['They believed they had won the western land in the war and were now banned from it',
   'It raised the price of tea that they bought from the East India Company',
   'It forced them to house British soldiers inside their own homes',
   'It gave the western land to France even though Britain had won'], 0,
  'What did colonists think they had been fighting for?',
  ['Colonists had fought to open the Ohio Valley to settlement.',
   'The Proclamation closed it.',
   'It felt like Britain was deciding their future for them.'],
  '**They had fought for that land and were now banned from it.** Many simply ignored the line.',
  'Tea and housing soldiers are later complaints, from topic 2.2.'),
 (2, "What was Pontiac's Rebellion?",
  ['A Native uprising against British forts after France left North America',
   'A colonial protest in Boston against the Stamp Act',
   'A French attempt to win back Canada after the Treaty of Paris',
   'A slave revolt in Virginia during the French and Indian War'], 0,
  'Who was Pontiac?',
  ['Pontiac was an Ottawa leader.', 'With France gone, Native nations faced British settlers with no ally.',
   'In 1763 they attacked British forts in the west.'],
  "**A Native uprising against British forts.** It is the reason Britain issued the Proclamation of 1763.",
  'Cause and effect: Pontiac\'s Rebellion → Proclamation of 1763.'),
 (3, 'How did the French and Indian War help lead to the American Revolution?',
  ['Its debt led Britain to tax the colonies, and its end removed France as a threat',
   'It left the colonies under French rule, which they then rebelled against',
   'It taught colonists that Britain would always protect them for free',
   'It made Native nations the colonists\' main enemy for the next century'], 0,
  'Think about money, and about who the colonists no longer needed protecting from.',
  ['Britain\'s war debt led to new taxes on the colonies.',
   'With France gone, colonists needed British soldiers less.',
   'Taxes plus less need for protection made them more willing to resist.'],
  '**The debt brought taxes, and the win removed France as a threat.** Colonists were asked to pay more just as they needed Britain less.',
  'That two-part answer is exactly the shape a short-answer question will want.'),
 (3, 'Put these events in order, earliest first.',
  ['Washington surrenders Fort Necessity',
   'The Treaty of Paris ends the French and Indian War',
   "Pontiac's Rebellion begins",
   'Britain issues the Proclamation of 1763'], 0,
  'Start with how the war began and end with Britain\'s response in the west.',
  ['1754: Washington surrenders Fort Necessity.', 'February 1763: the Treaty of Paris.',
   "Spring 1763: Pontiac's Rebellion.", 'October 1763: the Proclamation.'],
  '**Fort Necessity → Treaty of Paris → Pontiac → Proclamation.** Three of the four happen in 1763, which is why the order within that year matters.',
  'The Proclamation is Britain\'s answer to Pontiac, so it has to come after.', None, 'order'),
 (3, 'Before 1763, Britain mostly let the colonies run themselves. What changed after the war?',
  ['Britain began enforcing its rules and taxes on the colonies much more strictly',
   'Britain gave the colonies their independence as a reward for fighting',
   'Britain stopped trading with the colonies altogether after the war',
   'Britain let France govern the colonies to save itself money'], 0,
  'Think about the war debt.',
  ['Britain needed money after the war.', 'It began enforcing trade laws it had ignored.',
   'It also passed new taxes on the colonies.'],
  '**Britain began enforcing its rules and taxes much more strictly.** The easy-going era was over.',
  'That easy-going era has a name — salutary neglect — and it is a topic in 2.2.'),
],
 "Section 2.1 of the teacher's Unit 2 test-topics list: the causes of the French and Indian War, George Washington's part in it, Native Americans, the Treaty of Paris of 1763, the war's effects and the Proclamation of 1763.",
 'Every tax and protest in the next section grows out of how this war ended — so this part is the "why" behind the whole unit.',
 [('Explain the causes of the French and Indian War', 'source'),
  ("Describe George Washington's role and the part Native Americans played", 'source'),
  ('Explain what the Treaty of Paris of 1763 decided', 'source'),
  ('Explain the effects of the war, including the Proclamation of 1763', 'source')],
 "Built from the teacher's Unit 2 TEST-TOPICS list, which names what is tested but says nothing about it — her class notes and textbook pages for this unit are not in Drive. So the facts here are standard US history, and every card and question is marked as our addition rather than as class material. Worth checking one or two against her own notes. The one trap to point out: \"Treaty of Paris\" appears in BOTH section 2.1 and section 2.3 of her list, and they are two different treaties — 1763 ends this war, 1783 ends the Revolution. The syllabus says exams include fill-in-the-blank and short answer, which multiple choice cannot practise, so saying each card aloud before flipping is the best use of the deck.",
 ('Say each card out loud before you flip it — the test has fill-in-the-blanks.', 15),
 '2.1')

# ══ Part 2 · The Road to Revolution (topics 2.2) ═════════════════════════════
part(2, 'The Road to Revolution', [
 ('Salutary neglect',
  '**Britain\'s old habit of NOT strictly enforcing its laws on the colonies.**\n'
  '• For decades, trade laws went mostly unenforced and the colonies governed themselves.\n'
  '• It ended after the French and Indian War, when Britain needed money.',
  '"Salutary" means healthy — the neglect was good for the colonies.'),
 ('The Sugar Act (1764)',
  '**A tax on sugar and molasses brought into the colonies — and, this time, actually enforced.**\n'
  '• It came with new rules for catching smugglers.',
  'The first of the new taxes after the war.'),
 ('The Stamp Act (1765)',
  '**A direct tax on printed paper: newspapers, legal documents, even playing cards.**\n'
  '• Everyone who read or signed anything paid it.\n'
  '• Protest was so fierce that Parliament repealed it in 1766.',
  'Paper needed a paid-for stamp.'),
 ('"No taxation without representation"',
  '**The colonists\' argument that only their own elected assemblies could tax them.**\n'
  '• The colonies had no members in Parliament.\n'
  '• So, they argued, Parliament had no right to tax them.',
  'No vote in Parliament → no tax from Parliament.'),
 ('The Boston Massacre (1770)',
  '**British soldiers fired into a crowd in Boston, killing five colonists.**\n'
  '• Crispus Attucks, a man of African and Native descent, was among those killed.\n'
  '• Paul Revere\'s engraving of it spread anger through the colonies.',
  'Five dead, and a picture that went everywhere.'),
 ('The Tea Act (1773)',
  '**A law giving the British East India Company control of the tea trade in the colonies.**\n'
  '• It made tea cheaper — but kept the tax on it.\n'
  '• Colonists saw it as a trick to make them accept Parliament\'s right to tax.',
  'Cheaper tea, same principle.'),
 ('The Boston Tea Party (1773)',
  '**Colonists dumped over 300 chests of East India Company tea into Boston Harbor.**\n'
  '• It was a protest against the Tea Act and the tax on tea.\n'
  '• Britain answered with harsh laws that closed Boston\'s port.',
  'Tea in the harbour, and Britain cracked down.'),
 ('Lexington and Concord (April 1775)',
  '**The first battles of the American Revolution, outside Boston.**\n'
  '• British soldiers marched to seize colonial weapons at Concord.\n'
  '• Colonial militia met them — "the shot heard round the world".',
  'Where the shooting war began.'),
 ('The Enlightenment',
  '**A movement of thinkers who believed reason could improve government and society.**\n'
  '• Their ideas gave the colonists arguments for self-government.',
  'Reason, not tradition, should decide how people are ruled.'),
 ('John Locke',
  '**An English thinker who said people are born with natural rights: life, liberty and property.**\n'
  '• Government gets its power from the consent of the governed.\n'
  '• If a government breaks that trust, the people may replace it.',
  'Life, liberty, property — and the right to change a bad government.'),
 ('Montesquieu',
  '**A French thinker who argued that power should be split between separate branches of government.**\n'
  '• Separation of powers keeps any one part from becoming too strong.',
  'Split the power so no one holds it all.'),
 ('Inalienable rights',
  '**Rights so basic that no government can take them away.**\n'
  '• The Declaration of Independence names life, liberty and the pursuit of happiness.\n'
  '• "Inalienable" and "unalienable" mean the same thing.',
  'In-alien-able: they can never be made someone else\'s.'),
 ('Common Sense (1776)',
  '**A pamphlet by Thomas Paine arguing, in plain words, that the colonies should declare independence.**\n'
  '• It was one of the best-selling publications of its time.\n'
  '• It turned many colonists from protesting taxes toward wanting independence.',
  'Paine wrote for ordinary readers, not scholars.'),
], [
 (1, 'What was salutary neglect?',
  ["Britain's habit of not strictly enforcing its laws on the colonies",
   "Britain's habit of taxing the colonies without asking them first",
   "The colonists' habit of ignoring the Native nations to their west",
   "The colonists' habit of refusing to buy any British goods at all"], 0,
  '"Neglect" means leaving something alone.',
  ['For decades Britain did not enforce its trade laws strictly.',
   'The colonies largely ran their own affairs.',
   'That hands-off policy is salutary neglect.'],
  "**Britain's habit of not strictly enforcing its laws on the colonies.** It ended after 1763.",
  'Its END is what makes it a test topic: the new taxes only feel new because enforcement had been so loose.'),
 (2, 'Why did salutary neglect come to an end?',
  ['Britain needed money after the French and Indian War',
   'The colonists asked Britain to govern them more closely',
   'France took over enforcing the laws in North America',
   'Parliament gave the colonies seats and votes of their own'], 0,
  'What did the French and Indian War leave Britain with?',
  ['The war left Britain deeply in debt.', 'To raise money it began enforcing old laws and adding new taxes.',
   'That ended the hands-off era.'],
  '**Britain needed money after the war.** The debt turned neglect into enforcement.',
  'Cause from 2.1, effect in 2.2 — the two sections connect here.'),
 (1, 'What did the Stamp Act tax?',
  ['Printed paper, such as newspapers and legal documents',
   'Tea brought into the colonies from India and China',
   'Sugar and molasses brought in from the Caribbean',
   'Land that colonists settled west of the mountains'], 0,
  'The "stamp" was put on something.',
  ['The Stamp Act of 1765 required a paid-for stamp on printed paper.',
   'Newspapers, legal documents and even playing cards were taxed.',
   'Almost every colonist paid it.'],
  '**Printed paper.** It touched nearly everyone, which is why the protest was so widespread.',
  'Sugar and molasses are the Sugar Act; tea is the Tea Act.'),
 (2, 'What did colonists mean by "no taxation without representation"?',
  ['Only an assembly they elected should be able to tax them',
   'They should never have to pay any taxes to anyone',
   'Britain should send more soldiers to protect them',
   'Taxes should be paid only by people who own land'], 0,
  'Did the colonies have members in Parliament?',
  ['The colonies elected no members to Parliament.',
   'So Parliament did not represent them.',
   'They argued only their own elected assemblies could tax them.'],
  '**Only an assembly they elected should tax them.** The objection was about who taxed them, not taxes as such.',
  'This is the key idea of the whole section — most protests trace back to it.'),
 (1, 'What happened at the Boston Massacre in 1770?',
  ['British soldiers fired into a crowd and killed five colonists',
   'Colonists dumped chests of British tea into Boston Harbor',
   'Colonial militia fought British troops at Lexington',
   'Colonists burned the homes of British tax collectors'], 0,
  'It involved soldiers and a crowd.',
  ['In March 1770 a crowd in Boston confronted British soldiers.',
   'The soldiers fired.', 'Five colonists were killed, including Crispus Attucks.'],
  '**British soldiers fired into a crowd and killed five colonists.**',
  'The tea goes in the harbour three years later, in 1773.'),
 (3, "Paul Revere's famous engraving of the Boston Massacre shows soldiers firing in a neat line at calm, unarmed townspeople. Why do historians call it propaganda?",
  ['It showed the event in a one-sided way to make colonists angry at Britain',
   'It was drawn many years later by someone who never visited Boston',
   'It was published by the British government to frighten the colonists',
   'It accurately showed every detail, so it could be used as evidence'], 0,
  'Was the scene really that orderly and one-sided?',
  ['The real event was a chaotic street confrontation.',
   'The engraving shows orderly soldiers firing on peaceful people.',
   'That picture was designed to stir anger, not to record what happened.'],
  '**It showed the event one-sidedly to make colonists angry.** A primary source can be real AND biased.',
  'Asking "who made this, and why?" is the first move with any primary source.'),
 (2, 'What did the Tea Act of 1773 actually do?',
  ['It gave the East India Company control of the tea trade and kept the tax on tea',
   'It banned the colonists from drinking any tea that was not grown in Britain',
   'It doubled the price of tea to pay for the French and Indian War',
   'It removed every tax on tea to win the colonists back'], 0,
  'Tea actually got cheaper. So why were colonists angry?',
  ['The Tea Act let the East India Company sell tea directly to the colonies.',
   'That made tea cheaper, but the tax on it stayed.',
   'Buying it meant accepting Parliament\'s right to tax.'],
  '**It gave the East India Company control of the tea trade and kept the tax.** Cheaper tea was a trap of principle.',
  'Many students assume the Tea Act made tea more expensive. It did the opposite.'),
 (1, 'What was the Boston Tea Party?',
  ['Colonists dumped East India Company tea into Boston Harbor in protest',
   'Colonists held a celebration in Boston when the Stamp Act was repealed',
   'British soldiers seized tea from Boston merchants who were smuggling',
   'Colonial leaders met in Boston to plan a boycott of British goods'], 0,
  'It was a protest, not a party.',
  ['In December 1773, colonists boarded ships in Boston Harbor.',
   'They dumped over 300 chests of tea into the water.',
   'It was a protest against the Tea Act.'],
  '**Colonists dumped East India Company tea into Boston Harbor.**',
  'Britain\'s answer — closing Boston\'s port — pushed the colonies closer together.'),
 (1, 'Why are the battles of Lexington and Concord important?',
  ['They were the first battles of the American Revolution',
   'They were the last battles of the French and Indian War',
   'They were the battles that ended the American Revolution',
   'They were the battles where the French joined the colonists'], 0,
  'Think "the shot heard round the world".',
  ['In April 1775 British troops marched to seize weapons at Concord.',
   'Colonial militia met them at Lexington and Concord.',
   'The fighting that day began the Revolutionary War.'],
  '**They were the first battles of the Revolution.**',
  'The end of the war is Yorktown, in topic 2.3.'),
 (2, 'Which idea is John Locke best known for?',
  ['People have natural rights to life, liberty and property',
   'Government power should be split into separate branches',
   'A king rules because God chose him to rule',
   'The strongest nation should rule over the weaker ones'], 0,
  'He gave the colonists their argument about rights.',
  ['Locke argued people are born with natural rights.',
   'He named them life, liberty and property.',
   'A government that breaks them can be replaced.'],
  '**Natural rights to life, liberty and property.** The Declaration echoes him.',
  'Separation of powers is Montesquieu. Keep the two apart.'),
 (2, 'Which Enlightenment thinker argued that government power should be split into separate branches?',
  ['Montesquieu', 'John Locke', 'Thomas Paine', 'George Washington'], 0,
  'Separation of powers.',
  ['Montesquieu argued no single part of government should hold all the power.',
   'He wanted power split among separate branches.',
   'The US Constitution later uses exactly that idea.'],
  '**Montesquieu.** Separation of powers is his idea.',
  'Locke = natural rights. Montesquieu = separation of powers.'),
 (2, 'In this passage, what does the word "unalienable" mean?',
  ['Rights that cannot be taken away or given up',
   'Rights that only citizens born in America have',
   'Rights that the king may grant or take back',
   'Rights that apply only to people who own land'], 0,
  'Look at the word: un-alien-able.',
  ['"Alienable" means able to be given or taken away.',
   '"Un-" reverses it.', 'So unalienable rights can never be taken away.'],
  '**Rights that cannot be taken away.** "Unalienable" and "inalienable" are the same word.',
  'You will also see it written "inalienable" — the Declaration itself says "unalienable".', DECL),
 (3, 'Which Enlightenment thinker\'s ideas does this passage most clearly echo?',
  ['John Locke, who wrote about natural rights to life and liberty',
   'Montesquieu, who wrote about separating the powers of government',
   'Thomas Paine, who wrote Common Sense in plain language',
   'George Washington, who led the army at Lexington and Concord'], 0,
  'Which thinker listed life and liberty as natural rights?',
  ['The passage names rights to life and liberty.',
   'Locke wrote that people are born with rights to life, liberty and property.',
   'Jefferson swapped "property" for "the pursuit of Happiness".'],
  "**John Locke.** Life and liberty come straight from Locke's natural rights.",
  "Washington did not fight at Lexington — he took command later that summer.", DECL),
 (2, 'What was the main argument of Thomas Paine\'s Common Sense?',
  ['The colonies should break away from Britain and become independent',
   'The colonies should pay Britain\'s war debt to show their loyalty',
   'The colonies should ask the king for seats in Parliament',
   'The colonies should join France against the British army'], 0,
  'What did it turn protesters into?',
  ['Common Sense was published in January 1776.',
   'It argued plainly that independence was the only sensible choice.',
   'It persuaded many colonists who had only wanted fairer taxes.'],
  '**The colonies should become independent.** It moved the argument from taxes to independence.',
  'Seats in Parliament is what some colonists wanted before 1776 — Paine argued against it.'),
 (3, 'What is Thomas Paine arguing in this passage?',
  ['It makes no sense for a small island to rule a whole continent',
   'The colonies should take over the island of Britain by force',
   'Britain is too far away to trade with the colonies',
   'Every continent should have its own king'], 0,
  'What is the "continent", and what is the "island"?',
  ['The continent is North America; the island is Britain.',
   'Paine calls it absurd for the island to govern the continent forever.',
   'So independence is just common sense.'],
  '**It makes no sense for an island to rule a continent.** The size comparison is his whole point.',
  'Plain comparisons like this are why ordinary colonists found Paine convincing.', PAINE2),
 (3, 'Put these events in order, earliest first.',
  ['The Sugar Act', 'The Stamp Act', 'The Boston Massacre', 'The Boston Tea Party'], 0,
  'Two acts, then two events in Boston.',
  ['1764: the Sugar Act.', '1765: the Stamp Act.', '1770: the Boston Massacre.',
   '1773: the Boston Tea Party.'],
  '**Sugar Act → Stamp Act → Boston Massacre → Boston Tea Party.** 1764, 1765, 1770, 1773.',
  'The two acts come first — the protests in Boston grow out of them.', None, 'order'),
 (3, 'Why did the Stamp Act anger colonists more than the Sugar Act?',
  ['It was a direct tax that almost everyone paid, not just merchants',
   'It was the first tax Britain had ever placed on any colony',
   'It raised far more money than every other tax put together',
   'It was passed by the colonial assemblies instead of Parliament'], 0,
  'Who paid each one?',
  ['The Sugar Act mostly hit merchants who imported molasses.',
   'The Stamp Act taxed newspapers, documents and more.',
   'Almost every colonist paid it directly, so almost everyone was angry.'],
  '**It was a direct tax that almost everyone paid.** Protest spread because the cost did.',
  'That breadth is also why it was repealed within a year.'),
],
 "Section 2.2 of the teacher's Unit 2 test-topics list: salutary neglect, the Sugar, Stamp and Tea Acts, the Boston Massacre and Tea Party, Lexington and Concord, the Enlightenment thinkers, inalienable rights and Common Sense.",
 'This is the chain of cause and effect that takes the colonies from loyal subjects to open war — the most-tested part of the unit.',
 [('Explain salutary neglect and why it ended', 'source'),
  ('Describe the Sugar, Stamp and Tea Acts and the colonial response to each', 'source'),
  ('Explain the Boston Massacre, the Boston Tea Party and Lexington and Concord', 'source'),
  ('Connect Enlightenment ideas and inalienable rights to the Revolution', 'source'),
  ('Explain the argument of Common Sense', 'source')],
 "Built from the teacher's Unit 2 test-topics list, which names what is tested but says nothing about it; her class notes and textbook pages for this unit are not in Drive, so the facts are standard US history and every card and question is marked as our addition. Three short primary-source passages are quoted exactly — two lines of the Declaration of Independence and one of Common Sense — since her syllabus says exams include primary sources. Two traps are built in on purpose. The Tea Act made tea CHEAPER, not dearer; the anger was about accepting the tax, and one question offers the \"doubled the price\" answer as a real wrong option. And Locke versus Montesquieu: natural rights against separation of powers, asked both ways round. Her list writes \"inalienable\"; the Declaration writes \"unalienable\" — the card says they are the same word.",
 ('Say the chain out loud: debt, taxes, protest, war.', 18),
 '2.2')

# ══ Part 3 · The War for Independence (topics 2.3) ════════════════════════════
part(3, 'The War for Independence', [
 ('British advantages',
  '**Britain had the world\'s strongest navy, a trained professional army, and far more money.**\n'
  '• It also had Loyalists and many Native nations on its side.',
  'Navy, army, money.'),
 ('British disadvantages',
  '**Britain was fighting 3,000 miles from home, on land it did not know.**\n'
  '• Every soldier and supply had to cross the Atlantic.\n'
  '• The war was not popular with everyone in Britain.\n'
  '• It hired German soldiers (Hessians), who had little reason to fight hard.',
  'Distance was Britain\'s biggest enemy.'),
 ('Colonial advantages',
  '**The colonists fought on home ground, for a cause they believed in, with strong leaders.**\n'
  '• George Washington kept the army together.\n'
  '• After 1778, France sent money, soldiers and ships.',
  'Home ground, a cause, and later, France.'),
 ('Colonial disadvantages',
  '**The colonists started with no navy, untrained soldiers, little money and constant shortages.**\n'
  '• Many colonists were Loyalists or did not take sides.',
  'Short of almost everything except determination.'),
 ('The Battle of Saratoga (1777)',
  '**The turning point of the war: a whole British army surrendered in New York.**\n'
  '• The victory convinced France that the Americans could win.\n'
  '• France then joined the war as an ally in 1778.',
  'Saratoga won France.'),
 ('Valley Forge (winter 1777–78)',
  '**The Continental Army\'s brutal winter camp in Pennsylvania.**\n'
  '• Soldiers lacked food, shoes and blankets; many died of disease.\n'
  '• Baron von Steuben drilled them into a disciplined army by spring.',
  'The army nearly broke — and came out tougher.'),
 ('The Battle of Yorktown (1781)',
  '**The last major battle: the British general Cornwallis surrendered in Virginia.**\n'
  '• American and French troops surrounded him on land.\n'
  '• The French navy blocked him from escaping by sea.',
  'Trapped between an army and a navy.'),
 ('The Treaty of Paris of 1783',
  '**The treaty that ENDED the American Revolution.**\n'
  '• Britain recognised the United States as independent.\n'
  '• The new country\'s western border reached the Mississippi River.',
  '1783 — the SECOND Treaty of Paris. The first, in 1763, ended the French and Indian War.'),
 ('Two treaties of Paris',
  '**1763 ended the French and Indian War; 1783 ended the American Revolution.**\n'
  '• Same city, same name, two different wars, twenty years apart.',
  '1763 beat France. 1783 freed the colonies.'),
 ('Phillis Wheatley',
  '**An enslaved African woman in Boston who became the first African American woman to publish a book of poetry (1773).**\n'
  '• She was named after the ship that brought her from Africa, the Phillis.\n'
  '• She wrote a poem to George Washington, and he invited her to meet him.\n'
  '• You may see it spelled "Phyllis" — she spelled it Phillis.',
  'Named for a ship; famous for a book.'),
 ('Elizabeth Freeman',
  '**An enslaved woman in Massachusetts who sued for her freedom in 1781 and won.**\n'
  '• She argued that the state\'s new constitution said "all men are born free and equal".\n'
  '• Her case helped end slavery in Massachusetts.',
  'She used the Revolution\'s own words to free herself.'),
], [
 (1, 'Which was a British advantage in the Revolutionary War?',
  ["The world's strongest navy and a trained professional army",
   'Fighting on home ground that its soldiers knew well',
   'A population that was united in wanting the war',
   'Short supply lines running straight from Britain'], 0,
  'Think about what Britain already had before the war began.',
  ['Britain had the most powerful navy in the world.', 'Its army was trained and professional.',
   'It also had far more money than the colonies.'],
  "**The world's strongest navy and a trained army.**",
  'Home ground and short supply lines were the colonists\' advantages — and Britain\'s problems.'),
 (2, 'Which was the biggest DISADVANTAGE for Britain?',
  ['It was fighting 3,000 miles from home, so every supply crossed an ocean',
   'It had no navy at all, so it could not reach the colonies',
   'It had no trained soldiers and relied only on local militia',
   'It had no money to pay for the war after the French left'], 0,
  'Where was the war being fought, compared with where Britain is?',
  ['The war was fought in North America.', 'Britain is across the Atlantic Ocean.',
   'Every soldier, gun and meal had to be shipped over.'],
  '**It was fighting 3,000 miles from home.** Distance made everything slow and expensive.',
  'The other three options describe the COLONISTS, not Britain.'),
 (2, 'Which was a colonial DISADVANTAGE at the start of the war?',
  ['No navy, untrained soldiers and very little money',
   'Fighting far from home on land they did not know',
   'Soldiers who were hired from Germany and did not care',
   'A war that was unpopular with people back in Britain'], 0,
  'What did the colonists NOT have?',
  ['The colonies had no navy at first.', 'Many soldiers were untrained militia.',
   'They had little money and constant shortages.'],
  '**No navy, untrained soldiers and little money.**',
  'The other three are British disadvantages. Sorting them by side is a likely test question.'),
 (2, 'Why was the Battle of Saratoga a turning point?',
  ['The American victory convinced France to join the war as an ally',
   'It was the first battle of the war, so it started the Revolution',
   'It was the last battle of the war, so it ended the Revolution',
   'The British captured Washington there and nearly won the war'], 0,
  'What did the rest of the world think after Saratoga?',
  ['In 1777 an entire British army surrendered at Saratoga.',
   'France saw that the Americans could actually win.',
   'In 1778 France became an ally, sending money, troops and ships.'],
  '**It convinced France to join the war.** French help is what made victory possible.',
  'First battle = Lexington and Concord. Last major battle = Yorktown.'),
 (2, 'What happened at Valley Forge?',
  ['The Continental Army suffered a brutal winter but came out better trained',
   'The Continental Army won its most important battle of the war there',
   'The British army surrendered there and the war came to an end',
   'The colonies signed the Declaration of Independence there'], 0,
  'It was a camp, not a battle.',
  ['In the winter of 1777–78 the army camped at Valley Forge, Pennsylvania.',
   'Soldiers lacked food, shoes and blankets, and many died of disease.',
   'Baron von Steuben drilled them into a disciplined force.'],
  '**The army suffered a brutal winter but came out better trained.**',
  'Valley Forge is about survival and training, not a battle — a common mix-up.'),
 (1, 'What happened at the Battle of Yorktown in 1781?',
  ['The British general Cornwallis surrendered, effectively ending the war',
   'The colonists fired the first shots of the Revolutionary War',
   'France agreed to join the war on the American side',
   'Washington\'s army spent a hard winter camped in the snow'], 0,
  'It is the last big battle.',
  ['American and French troops surrounded Cornwallis in Virginia.',
   'The French navy stopped him escaping by sea.', 'He surrendered, and the fighting was effectively over.'],
  '**Cornwallis surrendered, effectively ending the war.**',
  'France joining is Saratoga; the hard winter is Valley Forge; the first shots are Lexington.'),
 (3, 'Why did the French navy matter so much at Yorktown?',
  ['It blocked Cornwallis from escaping or being rescued by sea',
   'It carried Washington\'s whole army across the Atlantic',
   'It captured London while the British army was in Virginia',
   'It supplied the British army with food during the siege'], 0,
  'Cornwallis was on the coast. How would he normally get out?',
  ['Cornwallis was trapped against the coast in Virginia.',
   'He expected the British navy to rescue him.',
   'The French fleet blocked the British ships, so no rescue came.'],
  '**It blocked Cornwallis\'s escape by sea.** Surrounded on land and sea, he had to surrender.',
  'This is why Saratoga matters twice: it won France, and France won Yorktown.'),
 (1, 'What did the Treaty of Paris of 1783 do?',
  ['Ended the Revolution and recognised the United States as independent',
   'Ended the French and Indian War and gave Canada to Britain',
   'Made France and the colonies allies against Britain',
   'Banned colonists from settling west of the mountains'], 0,
  'Which war ended in 1783?',
  ['1783 is the end of the American Revolution.', 'Britain recognised the United States as independent.',
   'The new western border reached the Mississippi River.'],
  '**It ended the Revolution and recognised American independence.**',
  'The 1763 treaty of the same name ended the French and Indian War.'),
 (3, 'History books mention a Treaty of Paris in 1763 AND in 1783. Why?',
  ['There were two treaties: 1763 ended the French and Indian War, 1783 ended the Revolution',
   'It is one treaty, first signed in 1763 and then signed again in 1783 by the same kings',
   'It is one treaty that ended both the French and Indian War and the Revolution in 1783',
   'The 1763 date is a misprint — there was only ever one treaty, signed in Paris in 1783'], 0,
  'Which war ended in 1763, and which in 1783?',
  ['In 1763 a Treaty of Paris ended the French and Indian War.',
   'In 1783 another Treaty of Paris ended the American Revolution.',
   'Same city and name — two different treaties, twenty years apart.'],
  '**There were two treaties: 1763 and 1783.** Check the date, and you know which war.',
  'On the test, the date or the context will tell you which one is meant.'),
 (1, 'Who was Phillis Wheatley?',
  ['The first African American woman to publish a book of poetry',
   'An enslaved woman who sued Massachusetts for her freedom',
   'A Loyalist who spied for the British army in New York',
   'A nurse who cared for soldiers at Valley Forge'], 0,
  'She is famous for writing.',
  ['Phillis Wheatley was brought from Africa and enslaved in Boston.',
   'She learned to read and write, and wrote poetry.',
   'In 1773 she became the first African American woman to publish a book of poems.'],
  '**The first African American woman to publish a book of poetry.**',
  'Suing for freedom is Elizabeth Freeman — the other woman on your list.'),
 (2, 'Who was Elizabeth Freeman?',
  ['An enslaved woman who sued for her freedom in Massachusetts and won',
   'The first African American woman to publish a book of poetry',
   'A woman who disguised herself as a man to fight in the army',
   'The wife of a general who ran his farm during the war'], 0,
  'She went to court.',
  ['Elizabeth Freeman was enslaved in Massachusetts.',
   'In 1781 she sued for her freedom.', 'She argued the new state constitution — "all men are born free and equal" — included her, and won.'],
  '**An enslaved woman who sued for her freedom and won.** Her case helped end slavery in Massachusetts.',
  'Poetry is Phillis Wheatley. Keep the two women on your list apart by what each DID.'),
 (3, 'Why is Elizabeth Freeman\'s case connected to the ideas of the Revolution?',
  ['She used the promise that all people are born free and equal to win her own freedom',
   'She argued that enslaved people should be taxed like everyone else',
   'She used the Treaty of Paris of 1783 to prove she was a British subject',
   'She showed that the Enlightenment thinkers supported slavery'], 0,
  'What words did she take to court?',
  ["Massachusetts' new constitution said \"all men are born free and equal\".",
   'Freeman argued that those words applied to her.',
   'The court agreed — the Revolution\'s ideals, applied to someone they had left out.'],
  '**She used the promise of freedom and equality to win her own freedom.**',
  'This is a strong short-answer example of the gap between the Revolution\'s words and its reality.'),
 (3, 'Put these events in order, earliest first.',
  ['The Battle of Saratoga', 'The winter at Valley Forge', 'The Battle of Yorktown',
   'The Treaty of Paris'], 0,
  'Turning point, hard winter, final battle, peace.',
  ['October 1777: Saratoga.', 'Winter 1777–78: Valley Forge.', '1781: Yorktown.', '1783: the Treaty of Paris.'],
  '**Saratoga → Valley Forge → Yorktown → Treaty of Paris.**',
  'Saratoga and Valley Forge are only weeks apart — the win came just before the hardest winter.', None, 'order'),
 (2, 'Which pair correctly matches each side with one of its advantages?',
  ['Britain: a powerful navy. Colonists: fighting on home ground',
   'Britain: fighting on home ground. Colonists: a powerful navy',
   'Britain: a small army. Colonists: plenty of money',
   'Britain: short supply lines. Colonists: professional soldiers'], 0,
  'Who had ships? Who knew the land?',
  ['Britain had the strongest navy in the world.', 'The colonists fought on land they knew.',
   'So navy → Britain, home ground → colonists.'],
  '**Britain: a powerful navy. Colonists: fighting on home ground.**',
  'Short supply lines and professional soldiers were the colonists\' problems, reversed.'),
],
 "Section 2.3 of the teacher's Unit 2 test-topics list: British and colonial advantages and disadvantages, Saratoga, Valley Forge, Yorktown, Phillis Wheatley, Elizabeth Freeman and the Treaty of Paris of 1783.",
 'This is how a colony with no navy beat the most powerful empire in the world — and who was left out of the freedom it won.',
 [('Compare British and colonial advantages and disadvantages', 'source'),
  ('Explain why Saratoga, Valley Forge and Yorktown matter', 'source'),
  ('Describe Phillis Wheatley and Elizabeth Freeman', 'source'),
  ('Explain what the Treaty of Paris of 1783 decided', 'source')],
 "Built from the teacher's Unit 2 test-topics list, which names what is tested but says nothing about it; her class notes and textbook pages for this unit are not in Drive, so the facts are standard US history and every card and question is marked as our addition. Two things to know. Her list spells \"Phyllis Wheatley\"; she spelled her own name Phillis, after the ship that brought her from Africa, so the card teaches Phillis and says so — worth knowing which one her teacher expects on a fill-in-the-blank. And \"Treaty of Paris\" is listed under both 2.1 and 2.3 because there really are two; one question asks her to explain exactly that. The advantages-and-disadvantages questions are built so each wrong option is a real trait of the OTHER side, since sorting them by side is the likeliest question format.",
 ('Sort every fact by side: Britain or the colonists?', 16),
 '2.3')
